### ISSUE TITLE
Isabella: blank appearance screen - again

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#494] opened 2017-04-20 12:51 UTC
#454

[Isabella_no_appearance_2.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/943119/Isabella_no_appearance_2.zip)

CoC_1.0.2_mod_1.4.1.swf

**Comment by brrritssocold** [comment] 2017-04-20 13:32
Can you please describe how to reproduce the issue?

**Comment by DullDanger** [comment] 2017-04-20 13:51
I knocked her up, gave ovi elixir and after a few days appearance screen become blank.

**Comment by brrritssocold** [comment] 2017-04-20 14:31
Can confirm blank appearance screen

**Comment by brrritssocold** [comment] 2017-04-20 15:24
I may be able to fix this, but i will need a review by someone who knows more about the event system (and possibly Isabella pregnancy)

My analysis so far:
Looks like a mismatch of set number of pregnancy events vs actual number of handled pregnancy 
 events.

The pregnancy event for Isabella returns a event number 10 in the debugger due to [what is set with addPregnancyEventSet](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/5a1b15f1025a6fb84c59b0c1a202cf5b39a0dfd9/classes/classes/Scenes/NPCs/IsabellaScene.as#L19), [but the cases only go to 9](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/633fac0a9897309ec008cedfc99676844aad10c5/classes/classes/Scenes/NPCs/IsabellaFollowerScene.as#L261).
This causes the code to not output anything.

Was this tested after it was fixed with a2eeca793ed1c38a405de53ec38953c11f36bc0c ?

**Closed** 2017-04-21 09:37 UTC
