### ISSUE TITLE
### Overview

### ISSUE THREAD

**Issue by TheRealJohnLaRoche** [Kitteh6660/Corruption-of-Champions-Mod#1090] opened 2017-12-27 21:47 UTC
### Overview
	The Appearance and Stats tabs are not responding correctly.
	
### Game version
	1.0.2_mod_1.4.11
	
### Expected behavior
	To see related traits on combat and miscellaneous stats in Stats and a description of the Character's appearance in appearance
	
### Actual behavior
	Stats opens a blank panel and Appearance does nothing.

### Steps to reproduce the issue

Clicking on stats or appearance will cause the issue.

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

Sorry, how would I attach the .sol on GitHub? Or would it be a different file? Thank you!

**Comment by Stadler76** [comment] 2017-12-28 03:09
Duplicate of issue #1027

**Closed by Stadler76** 2017-12-28 03:09 UTC
