### ISSUE TITLE
Appearance and Stats tabs broken

### ISSUE THREAD

**Issue by Moofluff** [Kitteh6660/Corruption-of-Champions-Mod#1059] opened 2017-12-08 05:51 UTC
### Overview
	'Stats' and 'Appearance' tabs have stopped working for one of my save files.
	
### Game version
	1.0.2_mod_1.4.11
	
### Expected behaviour
	Clicking on 'Stats' brings up page showing character's stats. Clicking on 'Appearance' tab brings up character's appearance

	
### Actual behaviour
Clicking on 'Stats' bring up a blank page. Clicking on 'Appearance' makes no action - not even a blank page. 

### Steps to reproduce the issue

Just click the tabs.

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be remov
[broken_camp_tabs.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1541540/broken_camp_tabs.zip)

ed).

**Comment by Stadler76** [comment] 2017-12-10 02:04
Duplicate of issue #1027

**Closed** 2017-12-10 02:04 UTC
Labels: Duplicate
