### ISSUE TITLE
"Mirvanna" [new character template] inaccessible

### ISSUE THREAD

**Issue by dabblevision** [Kitteh6660/Corruption-of-Champions-Mod#738] opened 2017-06-26 17:12 UTC
### Overview
	Choosing to use SpecialName characteristics of name "Mirvanna" at character creation does not work
	
### Game version
	1.0.2_mod_1.4.7
	
### Expected behaviour
	When the "Next" button is clicked after choosing the name Mirvanna, 
    you get the option to adopt the premade character for that name or to "continue on" 
    and make your own character. Clicking the left button (not "Continue on") should then 
    change the text on the page to mirvanna's description and allow you to continue to choosing game difficulty.
	
### Actual behaviour
	Clicking the button to use the Mirvanna template blanks the text on the page and seemingly does 
    nothing else. You can still click "Continue on", but the Mirvanna template seems inaccessible.

### Steps to reproduce the issue

1. Start a new game
2. Choose character name "Mirvanna"
3. When notified that the name is special, click the button NOT labeled "Continue on"
--> faulty behavior

**Comment by brrritssocold** [comment] 2017-06-27 14:39
Confirmed, working on PR.

**Comment by brrritssocold** [comment] 2017-06-27 15:56
Beat me to it :smiley:

**Comment by Stadler76** [comment] 2017-06-28 16:12
Fixed and will be in the next release (**after** CoC Revamp 1.4.7). I you find more broken special characters in the next release, just open a new issue.

~closing~

**Closed by Stadler76** 2017-06-28 16:12 UTC
Labels: Bug

**Comment by brrritssocold** [comment] 2017-06-28 22:20
Working on a test case that will iterate through all special chars and execute the creation function.
This should trigger any runtime errors.
As a bonus, it should scale automatically for any future characters (since the whole thing is an array)
