### ISSUE TITLE
[Bug] All cocks too small for Isabella

### ISSUE THREAD

**Issue by ShadowMarker789** [Kitteh6660/Corruption-of-Champions-Mod#1397] opened 2018-12-20 11:15 UTC
### Overview
Isabella is a follower you can recruit, after you add her to camp, usually you can have vaginal sex with her if you have a cock, and it's not too big. In past versions, she used to accept cocks up (around) to 8 inches in length. In the current version, it appears that /all/ cocks are too big for her. In the current version I've never been able to have vaginal sex with her. I've gotten the cock length all the way down to 2.1 inches length, and 0.5 inches thick, and still cannot. 
	
### Game version
This report pertains to version 1.02_mod_1.4.15
	
### Expected behaviour
Should your cock length be around 8 inches or less (depending on girth) and you call for Isabella, you should be able to have vaginal sex with her.
	
### Actual behaviour
No matter how small your cock is, the button for sex with Isabella is always disabled.

### How often can this be reproduced?
Occurs every time, cannot be avoided. 

### Steps to reproduce the issue

1) Recruit Isabella
2) Get your cock length/girth suitable for Isabella (mashing reducto on the cock should be sufficient)
3) Call for Isabella
4) Enter sex menu
5) Notice that the vaginal sex option is disabled

**Comment by Fritterwhore** [comment] 2018-12-27 02:21
This is a duplicate of #1384 .

**Closed** 2018-12-28 18:43 UTC
