### ISSUE TITLE
[Bug Report]can't use stash option(for chest store and take)

### ISSUE THREAD

**Issue by jameson7856** [Kitteh6660/Corruption-of-Champions-Mod#1420] opened 2019-06-11 15:27 UTC
[Bug Report]
### Overview
 can't use stash option(for chest store and take)
	
### Game version
v1.4.16d for CoC 1.0.2
	
### Expected behaviour
In the stash option shall be able to store item and take item in the chest.
	
### Actual behaviour
try to store things it simply says no room for ıt and take option doesn't even shown.

### How often can this be reproduced?
everytime

**Comment by brrritssocold** [comment] 2019-06-13 13:09
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request

**Comment by brrritssocold** [comment] 2019-06-13 13:25
Cannot reproduce this with the release binary or current master.

Is this an old save that is loaded?

**Comment by Kitteh6660** [comment] 2019-06-14 09:16
Should be fixed in 1.4.17. If that is still an issue, let me know.

**Closed by Kitteh6660** 2019-06-14 09:16 UTC
