### ISSUE TITLE
[Bug] chest

### ISSUE THREAD

**Issue by TheNilar** [Kitteh6660/Corruption-of-Champions-Mod#1421] opened 2019-06-11 19:56 UTC
### Overview
Chest disapears after loading a save file.
	
### Game version
v1.4.16d for CoC 1.0.2
	
### Expected behaviour
Chest should still be there after loading a save file.
	
### Actual behaviour
says there are currently no storage.

### How often can this be reproduced?
everytime
### Steps to reproduce the issue

1. First step
Find the chest is desert.
2. Second step
Save
3. and so on...
load the save.

**Comment by brrritssocold** [comment] 2019-06-13 12:23
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request

**Comment by brrritssocold** [comment] 2019-06-13 13:07
Can confirm the issue with the release binary.

Commit 8a265887f8e304ef44a1b4ea89f7325140737289 is not CoC 1.0.2 - Mod v1.4.16d

Cannot reproduce issue with 8a265887f8e304ef44a1b4ea89f7325140737289, 6df1a97d240137616169fe8518f7c691ed352949 or d3202bae7682a8dc64bc2df5fe61d23bb435e2ad

Seems to be fixed in the master branch.

**Comment by Kitteh6660** [comment] 2019-06-14 09:17
Should be fixed in 1.4.17 now.

**Closed by Kitteh6660** 2019-06-14 09:17 UTC
