### ISSUE TITLE
[BUG] Unlimited Scarred Blades - Tel'Adre - Shops - Weapons

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#320] opened 2016-08-10 05:34 UTC
Acquired the Scarred Blade via the usual method, by corrupting Sheila and giving her Lethicite to the Weapons NPC in Tel'Adre. Waited a few days, came back, and picked up Scarred Blade. Returned a long while later, and Scarred Blade is still an option. Now he's giving me a Scarred Blade each time I click the option, with each selling for 500 Gems, and stacking up to 5 per Inventory Slot.

**Comment by JustGregory** [comment] 2016-08-10 06:37
Note, I haven't gone digging for the above, but on the basis of it, it sounds like in other games I've seen, that the quest or whatever should use an integer with values for "not obtainable", "obtainable", and "obtained" to specify at what stage of availability the item is. Obviously, code should check if the value means the item has already been obtained, by wrapping the event within an "if" statement. This ensures it cannot be obtained again (unless such is by design).

I guess it's the same as in CCGs/TCGs and RPGs, where cards or items would have a "rarity" to limit their availability. Problem being with this issue, it could make a rare item rather common. (Of course, the champion can still only equip one weapon at a time, so ... less of an issue from a power standpoint, more of an issue for item resellability. Personally if money were the issue, I'd just load the save in CoCEd and tweak in an amount of gems to keep me going for some time -- but oh well.)

**Comment by Darth-Cthoras** [comment] 2016-08-10 07:54
Gems are ridiculously easy to get, anyway, once you have virtually all level-up perks and some gear, given the high-end goblins drop everything from Reducto to Rings, all of which sell for 100 to 500.

**Comment by JustGregory** [comment] 2016-08-10 09:20
An obvious footnote to that, @Darth-Cthoras, is that I have a problem with what you being so "ridiculously easy to get" only so late into the game, all the while in earlier days I eke out a meager living just trying to scrape two gems together to buy more wood and nails for the camp house. It takes a lot more time to get a champion to a competitive point, at least after started getting familiar with the deep woods, high mountains, and so on, and even longer to get to the state you say.

To date the only way I've ever gotten a shield and other seriously effective gear has been by going into CoCEd and give myself max gems. This is at least in major part due to how "slow" the game feels when seeing what is purchasable in the armor, weapons, and other shops in Tel'Adre, compared to the pittance in gems I'm getting with goblin and imp encounters.

I'm perfectly willing to play non-cheaty ways if and only if the ways to get the same amount of resources would be available at lower levels. Maybe not "immediately" after arriving through the portal, but likely by something encounterable by the 2nd to 3rd week. Otherwise, forget the boning, it feels as if I'm playing only for the goal of getting to a higher level to take on more exotic/difficult creatures I haven't experienced yet. After all, as many times as I keep being sucked into Lumi's Laboratory on random exploration, I've got to believe that not all races in this game-universe have been known yet, and not all creatures give so very little resources.

If a non-cheaty way to get with gear, gems, and perks earlier in game is warranted, early-game CoC seriously needs either a new one-time major event or a new race or NPC repeat-encounter, or a combination of both, something that drops high amounts of stuff; my suggestion might be an offshoot of a goblin or imp tribe that wasn't as corrupted as their kin and perhaps retained knowledge of merchant trades and craftsmanships, might possibly be only slightly more difficult to beat than the common imp, and are more likely to carry gems or items. Such an event could disappear or lessen in encounterability after a certain limit is reached, so it's not an "indefinite cash cow" so to speak...

Or maybe occasionally randomly an opponent might beg to be released in return for gems or items, whatever's available (might be an alternative to always beating (up/down) the enemy in combat, or a way the creature could plead with the champion for release when defeated, instead of being killed or violated).

Or better yet: maybe somewhere in Marae is a secret stash of well-protected books and artifacts that the guy in Tel'Adre's tower would buy for some hefty sum. (Sure beats having to kill oneself cleaning old defaced books when a well-preserved near-original copy can be had; and for the life of me I don't recall anything being done with that guy otherwise, conversing with him ends up going around in circles about not bothering him.) And maybe the stash could be found rather early in-game - say, a "Vault" in the desert or something where old lore has been stored (possible Phylla's people know a little about it - though I don't consider Phylla "early game" content).

(Okay, I admit it, I've got an overactive imagination to dream up all this. I'm still more comfortable with coding Java than Flash, so in lieu of my own existing projects I may not exert that much effort coding for CoC; don't mind me if these ideas don't mesh with CoC ideals, but if they do, anyone can borrow them to code a few scenes.)

**Comment by Darth-Cthoras** [comment] 2016-08-10 10:41
@JustGregory Leather Armour and a Dagger can both be taken (and kept) from enemies in the Prologue. Gems are easy to get even at low levels on a fresh game, I find. The stationary Mimics you can run across, all by themselves, hand out gems like mad, either through moderately expensive drops, or flat out Gems. Depending on your style, you could also find and sell either one of the Wizard Staff or Beautiful Sword - especially if you're a female going for Raphael's rapier. Grab a bow and some mastery from Kelt early, and then you can spare yourself some extra gems by selling the other weapon. All this will very rapidly get you enough gems for a decent Shield, and then you're good to hunt for better stuff.

**Comment by JustGregory** [comment] 2016-08-10 12:25
That is certainly doable, although the way you are describing it makes it seem like a formulaic progression to the same end-result as I mentioned. Maybe just my misfortune, but aditional Raphael appearances didn't trigger for me..

(btw Never had considered selling the Beautiful Sword and using something else; I just kinda "assumed" it was a necessary item, as in "the Champion's One True Sword" kind of thing, to keep as un-corrupted as possible. -- It was found stuck in a tree trunk, see? Marae the giver of the "destroy the demon factory" quest appears from a tree trunk, see? Understand how I could connect the dots??)

**Comment by Darth-Cthoras** [comment] 2016-08-10 16:04
@JustGregory It's not -necessary-, just powerful - if you stay entirely uncorrupted. If you don't plan to, just sell it off and use anything else. The Scarred Blade is its opposite, and the Broken Scarred Blade is neutral and can be used by anyone. Also, you should read up on the Wiki if you're having troubles. [url]http://coc-revamp-mod.wikia.com/wiki/Main_Page[/url]

**Comment by Stadler76** [comment] 2016-08-10 17:06
For [Basilisk Eyes Phase 2](https://docs.google.com/document/d/1KgaLS5xm51yesCyI_WuGf6j69diwnOjbKHEkWue99Ac/edit#heading=h.yhbdqefupddb) I've made the hair-pin the player gets from Benoit(e) an equippable key-item. Player can't abandon it or sell it. It won't be lost in space in your inventory or any of your stashs and it will disappear upon ascension, so you need to get it back after ascending. Would that be an idea for the scarred blade?

**Comment by Darth-Cthoras** [comment] 2016-08-10 17:18
An equippable key item? That sounds... strange. Never heard of a Key Item that could be equipped, but it's a possibility, perhaps. Though having to get it after ascension seems a bit much given the sheer trouble it is to even acquire it, and the fact that all weapons except Bow and Kelt's Bow can be kept and stored.

**Comment by Stadler76** [comment] 2016-08-10 19:32
Well, then what about a new button in the ascension menu where you can choose to keep certain key-items? This won't be permanent and you'll have to select them again when you ascend again. And it won't cost you ascension points. Player can choose to keep or abandon the blade, when ascending. Note, that sometimes ppl. want to go through a certain quest chain again, even if this takes some time and effort.

**Comment by Darth-Cthoras** [comment] 2016-08-11 00:30
@Stadler76 Having a Scarred Blade already doesn't mean you can't do the quest next ascension. The NPC checks only for the Key Item - Sheila's Lethicite in your Key Item Inventory, and Sheila has no checks for the Scarred Blade, meaning you can repeat it for a new sword every Ascension.

**Comment by Stadler76** [comment] 2016-08-11 02:46
Yeah, and if you accidentally abandon it or if you sold it, you can always reload a savegame.
I guess, adding a new flag to handle this issue is probably the simplest solution.

**Comment by Kitteh6660** [comment] 2017-02-07 16:25
Should be patched in 1.4.

**Closed by Kitteh6660** 2017-02-07 16:25 UTC
