### ISSUE TITLE
Stats and appearance tabs broken after using goldenseeds.

### ISSUE THREAD

**Issue by ExaltedCat** [Kitteh6660/Corruption-of-Champions-Mod#1078] opened 2017-12-19 04:36 UTC
[COC Bugged Save.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1570393/COC.Bugged.Save.zip)

Overview:
Stats tab and appearance tab no longer work after using Goldenseeds.
	
Game version
1.0.2_mod_1.4.11
	
Expected behaviour:
Shouldn't effect how these tabs work.
	
Actual behaviour:
Stats tab opens but displays nothing and the appearance tab doesn't open at all. Happened the first time after about 25 of them. The second time happened after 6.

Steps to reproduce the issue:
Don't know how to run/work debug :/

**Comment by Stadler76** [comment] 2017-12-19 19:12
Duplicate of issue #1027

**Comment by Kitteh6660** [comment] 2017-12-29 04:40
I'll close this comment. Seems to work, let me know if this is still going to happen in 1.4.12.

**Closed by Kitteh6660** 2017-12-29 04:40 UTC
Labels: Duplicate
