### ISSUE TITLE
Masturbate option in camp randomly stops working

### ISSUE THREAD

**Issue by nuclearity** [Kitteh6660/Corruption-of-Champions-Mod#135] opened 2015-09-22 23:02 UTC
The masturbate button stops working seemingly randomly.
The button still appears when lust is high enough to masturbate but clicking on it results in what is shown in the image attached. Clicking on the masturbate option at this point does nothing and you can only get back to the camp menu by using the buttons in the top menu.

I don't know what triggers this but losing the lust and then regaining it does not restore the buttons functionality.
![bug](https://cloud.githubusercontent.com/assets/14795399/10034158/4136b342-6186-11e5-9887-bf89de3521af.png)

**Comment by ambjoorn94** [comment] 2015-09-23 06:41
A save file would probably help determine the cause

**Comment by nuclearity** [comment] 2015-09-23 09:05
Oh sure,
sry should've sent one immediately.
http://we.tl/6aM6RQvhfy

**Comment by ambjoorn94** [comment] 2015-09-23 09:42
It seems this bug happens while wearing Valeria as armor (GooArmr)
As a temporary measure, you may want to unequip your goo armor when you want to masturbate.

Permanent fix will be researched

**Comment by Kitteh6660** [comment] 2015-09-24 03:21
Found the cause of the crash. This will be fixed in next snapshot.

**Comment by Kitteh6660** [comment] 2015-09-27 18:33
Closed as it's now fixed. Let me know if the issue crops up.

**Closed by Kitteh6660** 2015-09-27 18:33 UTC
