### ISSUE TITLE
[BUG] Goblin Elder + Lethice Whip

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#272] opened 2016-07-14 04:51 UTC
Certain victories over Goblin Elder using Lethice's Flaming Whip (causing lust AND damage) while using Double Attack are triggering the victory text but causing gem loss and eight hours to pass.

**Comment by Darth-Cthoras** [comment] 2016-07-14 11:42
Just ran into this issue with Imp Overlord, too. Not sure, but I think I defeated him with both lust and damage simultaneously in the first half of my Double Attack.

**Comment by Darth-Cthoras** [comment] 2016-07-14 11:55
Just watched a battle with Goblin Elder - looks more and more like the your loss triggers when the FIRST half of a Lust+Damage attack causes them to lose by lust.... but only if the SECOND half would have caused them to lose by HP.

**Comment by Stadler76** [comment] 2016-07-14 20:27
I playtested this a little and I believe this depends on your corruption and your lust level. 
Don't forget, that using Lethice's Whip raises your corruption **and** occasionally your lust.
So I think, that this is actually intended behaviour.

PS: Can anyone point me to the code, where this is being handled? Would be nice.

**Comment by Darth-Cthoras** [comment] 2016-07-14 21:53
Except that my lust wasn't higher than 50s in almost every case when I lost, nor did it reset to minimum after the eight hours, as it should have if it was a lust/sex loss. So that negates the theory of lust rising to be the issue, no? Unfortunately, I have no clue where in the code this is all handled, and can't work on GitHub well on my phone - computer's at minimal functionality and has been for weeks, having to run Mini Windows XP Live from a disc just to access Flash Player, and can't get online.

**Comment by Kitteh6660** [comment] 2016-12-13 11:54
This should be fixed in 1.4.

**Closed** 2017-02-07 16:21 UTC
